logging:
  level:
    org:
      springframework:
        security:
          oauth2: INFO
        ws:
          server:
            MessageTracing:
              received: TRACE
              sent: TRACE
server:
  port: 8081
  servlet:
    context-path: /lambda-auth
    encoding:
      charset: UTF-8
      enabled: true
spring:
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 100000
      maxLifetime: 900000
      maximum-pool-size: 20
      minimum-idle: 10
    initialization-mode: never
    password: ${SPRING_DATASOURCE_PASSWORD:}
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      file-size-threshold: 5MB
      max-file-size: 10MB
  messages:
    basename: static/i18n/message
    encoding: UTF-8
folder:
  temp: /tmp
webservices:
  url:
    notification: http://192.168.0.100:8095/delta-notification/webservice/notification.wsdl
