logging:
  level:
    org:
      springframework:
        security:
          oauth2: INFO
        ws:
          server:
            MessageTracing:
              received: TRACE
              sent: TRACE
  config: classpath:log4j-spring.xml
server:
  port: 8081
  servlet:
    context-path: /lambda-auth
    encoding:
      charset: UTF-8
      enabled: true
spring:
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 100000
      maxLifetime: 900000
      maximum-pool-size: 20
      minimum-idle: 10
    initialization-mode: never
    url: jdbc:${CLEARDB_DATABASE_URL:}
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: static/i18n/message
    encoding: UTF-8
  servlet:
    multipart:
      file-size-threshold: 5MB
      max-file-size: 10MB
  mvc:
    static-path-pattern: /
    log-resolved-exception: true
    view:
      prefix: classpath:/templates
      suffix: .html
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: true
  devtools:
    add-properties: false
# Override by WebMvcConfig.class
#  web:
#    resources:
#      static-locations: classpath:/static/
storage:
  temp: /
  cloudinary:
    url: ${CLOUDINARY_URL:}
webservices:
  url:
    notification: https://delta-notification-service.herokuapp.com/delta-notification/webservice/notification.wsdl
security:
  oath2:
    resource-id: user
