logging:
  level:
    root: INFO
    org:
      springframework:
        security:
          oauth2: INFO
        ws:
          server:
            MessageTracing:
              received: TRACE
              sent: TRACE
        jdbc:
          core: TRACE
  config: classpath:log4j-spring.xml
server:
  port: 8082
  servlet:
    context-path: /lambda-auth
    encoding:
      charset: UTF-8
      enabled: true
  error:
    whitelabel:
      enabled: false
    path: /error
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  ssl:
    enabled: true
    enabled-protocols: TLSv1.2
    key-alias: ${SSL_KEY_ALIAS:}
    key-password: ${SSL_KEY_PASSWORD:}
    key-store: classpath:vengeance.jks
    key-store-password: ${SSL_KEYSTORE_PASSWORD:}
    key-store-type: JKS
    protocol: TLS
spring:
  redis:
    host: ${REDIS_HOST:}
    port: ${REDIS_PORT:}
    database: ${REDIS_DB:}
    password: ${REDIS_PASSWORD:}
  session:
    store-type: redis
    redis:
      namespace: lambda:auth:session
      flush-mode: on_save
      cleanup-cron: "0 * * * * *"
    timeout: 1h
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 100000
      maxLifetime: 900000
      maximum-pool-size: 20
      minimum-idle: 10
    initialization-mode: never
    password: v3ng34nc3
    url: jdbc:mysql://192.168.0.101:3306/user_management?useUnicode=true&characterEncoding=UTF-8
    username: root
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: static/i18n/message
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mvc:
    static-path-pattern: /
    log-resolved-exception: true
    view:
      prefix: classpath:/templates/
      suffix: .html
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: true
  devtools:
    add-properties: false
  banner:
    location: classpath:banner.txt
# Override by WebMvcConfig.class
#  web:
#    resources:
#      static-locations: classpath:/static/**
#      add-mappings: false
storage:
  storage-type: local
  temp: ${TEMP_DIR:}
  cloudinary:
    url: ${CLOUDINARY_URL:}
  firebase:
    database-url: ${FIREBASE_DATABASE_URL:}
    storage-bucket: ${FIREBASE_STORAGE_BUCKET:}
    credentials: ${FIREBASE_CREDENTIALS:}
  local:
    upload-dir: ${UPLOAD_DIR:}
webservices:
  url:
    notification: http://192.168.0.100:8095/delta-notification/webservice/notification.wsdl
security:
  oath2:
    resource-id: user
custom:
  http-port: 8081
  https-port: 8082
  security-policy: CONFIDENTAL
  connector-scheme: http
  trust-store-password: ${SSL_TRUSTSTORE_PASSWORD:}
  trust-store-type: JKS
